name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  phpstan:
    name: PHPStan + Pint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit=2G
      - name: Run Pint
        run: ./vendor/bin/pint --test
